# Generated by Django 5.0 on 2024-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_fornecedor_contato_fornecedor_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=190, null=True),
        ),
    ]
