# Generated by Django 5.0 on 2024-07-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_fornecedor_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='descricao',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='rua',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
    ]
