# Generated by Django 5.0 on 2024-07-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_delete_recebimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rua',
        ),
    ]
