# Generated by Django 5.0 on 2024-07-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_mensagem_lida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='lida',
        ),
    ]
