# Generated by Django 5.0 on 2024-07-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_registroacesso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroAcesso',
        ),
    ]
